version: '2'

services:
  angular:
    build: 'angular/'
    restart: always
    container_name: 'angular_client'
    networks:
      - web-app
    ports:
      - '8080:80'
      - '443:443'
  java:
    build: 'java/'
    restart: always
    container_name: 'java_client'
    ports:
      - 9090:8080
    networks:
      - web-app

networks:
  web-app:
    driver: bridge